# Generated by Django 2.2.1 on 2019-05-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='star',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
